channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=21.2.4
- pip:
  - mlflow==2.8.0
  - importlib-metadata==4.11.3
  - numpy==1.21.5
  - pandas==1.5.1
  - psutil==5.8.0
  - scikit-learn==1.0.2
  - scipy==1.7.3
  - xgboost==2.0.1
name: mlflow-env
